pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/SomtoEchegiri/sandwitch_fullstack.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install --legacy-peer-deps'
            }
        }

        stage('Build Angular App') {
            steps {
                sh 'npm run build --prod'
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Angular app...'
                // Add deployment steps here (e.g., copy files to a server)
            }
        }
    }
}
